# version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-local
    environment:
      POSTGRES_DB: scrape-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  redis:
    image: redis:latest
    container_name: redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - postgres_network

volumes:
  postgres_data:
  redis_data:

networks:
  postgres_network: